### ISSUE TITLE
Cocoapods

### ISSUE THREAD

**Issue by Istered** [kickstarter/Kickstarter-Prelude#79]
Hi. Any chance for Cocoapods support?

**Comment by justinswart** [comment]
We don't have any plans to add this, the library is fairly easy to use as a git submodule.

I'm not too familiar with cocoapods but I believe something like this _might_ be possible in your `Podfile`:

`pod "Kickstarter-Prelude", :git => "https://github.com/kickstarter/Kickstarter-Prelude.git", :submodules => true`

**Comment by zhigang1992** [comment]
I've add `Kickstarter-Prelude` and `Kickstarter-Prelude-UIKit` to cocoapods repo.

https://cocoapods.org/pods/Kickstarter-Prelude
https://cocoapods.org/pods/Kickstarter-Prelude-UIKit

https://github.com/zhigang1992/Kickstarter-Prelude/commit/ae732edd13b9ca8b2f87f858be7f77e4b628648d

@justinswart I'd love to help put these podspecs in this official repo, but it'd require the tags to be created here as well. Pls let me know. 😄
